// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GenBankProvider")>]
[<assembly: AssemblyProductAttribute("GenBankProvider")>]
[<assembly: AssemblyDescriptionAttribute("A type provider for GenBank data with the use of .NET Bio types")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GenBankProvider"
    let [<Literal>] AssemblyProduct = "GenBankProvider"
    let [<Literal>] AssemblyDescription = "A type provider for GenBank data with the use of .NET Bio types"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
